# Generated by Django 3.2.5 on 2021-07-20 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210720_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturls',
            name='delete_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 22, 47, 33, 241515)),
        ),
    ]
